name: happy_pet_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #State Management
  provider: ^4.3.2+3
  #UI
  readmore: ^1.0.0
  fluttericon: ^1.0.7
  dropdown_search:
  #Futures Reflections
  flutter_spinkit: "^4.1.2"
  flushbar: ^1.10.4
  # Firebase
  firebase_core: "0.7.0"
  firebase_auth: "^0.20.0+1"
  cloud_firestore: "^0.16.0"
  firebase_storage: "^7.0.0"



dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/AnimalsIcons/

